### ISSUE TITLE
!setflag - Bot response to include discord name of command user

### ISSUE THREAD

**Issue by BoomOSRS** [wise-old-man/discord-bot#118]
![image](https://user-images.githubusercontent.com/70453840/132565375-2d0718ba-b402-4582-8b7f-c77bca553af5.png)

The bot should also respond with the discord name (e.g Boom#0675 - not the nickname) of the person using the command. This will serve as a record of who has requested a flag for a specific rsn and allow us to take action to prevent repeated abuse of the feature if someone is trolling and setting incorrect flags for people they don't have permission from.

**Comment by Sethmare** [comment]
Even discord usernames can be changed, could we do their discord id? Or maybe both the username and discord id?

**Comment by Hydrox6** [comment]
How we do it with the RuneLite bot is to have all 3 things: clickable tag, id, and name#discrim
The name#discrim isn't as needed since that can get out of date, but the first two are very useful (with the ID mostly being needed because Discord can "fail to load" the tag)
![image](https://user-images.githubusercontent.com/2979691/132581826-16831853-18ce-47a9-93b9-eb4a18490d9d.png)

**Comment by Sethmare** [comment]
While we are at it, we may want to do the same thing to the group leader log
