### ISSUE TITLE
Show "Name Change ID" on confirmations

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/discord-bot#133]
As shown in this example, it would be useful to show the "name change id" to determine which name change approved/denied/failed.

i.e. `Failed to approve name change 48504.` or `✅ Name change 48499 approved: Kbd eez → Kq p`

![Screenshot_21](https://user-images.githubusercontent.com/66145237/148830312-f74dfe79-72ff-4329-8fa5-b4d22829540b.png)

**Comment by psikoi** [comment]
This is no longer needed since the success/error messages now appear as a footer to the original request command (and those commands have the name change ID in the prompt)

![Screenshot 2023-02-18 at 19 08 54](https://user-images.githubusercontent.com/3278148/219881619-b4b5f694-96b8-4803-9894-9168ffef0842.png)
